# Generated by Django 5.2.17 on 2026-08-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentlyBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='What is this project and what problem does it solve?')),
                ('technologies', models.CharField(help_text='Technologies being used, comma-separated', max_length=500)),
                ('status', models.CharField(choices=[('Planning', 'Planning'), ('In Development', 'In Development'), ('Testing', 'Testing'), ('Completed', 'Completed')], default='In Development', max_length=50)),
                ('progress_percent', models.IntegerField(default=50, help_text='Estimated progress from 0 to 100')),
                ('image', models.ImageField(blank=True, help_text='Project preview or architecture diagram', upload_to='building/')),
                ('github_url', models.URLField(blank=True, default='', help_text='GitHub URL if available')),
                ('live_url', models.URLField(blank=True, default='', help_text='Live demo/staging URL if available')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Currently Building Project',
                'verbose_name_plural': 'Currently Building Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_name', models.CharField(default='Scholastica Mutuku', max_length=200)),
                ('supervisor_role', models.CharField(default='Software Engineer', max_length=200)),
                ('organization', models.CharField(default='ICT Authority of Kenya', max_length=200)),
                ('organization_note', models.CharField(blank=True, default='State Corporation under Kenya State Corporations Act 446', max_length=300)),
                ('recommendation_date', models.CharField(default='20 July 2026', max_length=100)),
                ('attachment_duration', models.CharField(default='4 May 2026 – 31 July 2026 (13 Weeks)', max_length=100)),
                ('quote', models.TextField(default='Pavis Mugo Muruga successfully completed a 13-week industrial attachment at the ICT Authority of Kenya from 4 May 2026 to 31 July 2026. He demonstrated exceptional enthusiasm, commitment, strong willingness to learn, and practical technical competency in Python, Django, ICT support, and system development.', help_text='Main excerpt or recommendation statement from supervisor')),
                ('highlights', models.TextField(blank=True, default='Enthusiasm and strong commitment\nStrong willingness to learn and adapt quickly\nProficiency in Python and Django development\nSolid ICT support and troubleshooting capabilities\nHigh level of professionalism and positive attitude\nExcellent problem-solving abilities\nAbility to work independently and as part of a team\nEffective communication and collaborative skills\nQuick comprehension of new concepts and technologies\nDedication to delivering quality and dependable work', help_text='Supervisor highlighted attributes, one per line')),
                ('recommendation_letter', models.FileField(blank=True, help_text='Upload the official recommendation letter PDF', upload_to='recommendations/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Professional Recommendation',
                'verbose_name_plural': 'Professional Recommendations',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(blank=True, default='Developer / Attachment Student', help_text='Your role in this project', max_length=200),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='Pavis Mugo Muruga', max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='course',
            field=models.CharField(default='Bachelor of Science in Information Technology', max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.CharField(blank=True, default='2028 (Expected)', max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(default='Kirinyaga University', max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='level',
            field=models.CharField(default='Year 2', help_text='e.g., Year 2', max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.CharField(blank=True, default='Current', max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='duration',
            field=models.CharField(help_text='e.g., 13 weeks (4 May 2026 – 31 July 2026)', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('django', 'Django'), ('python', 'Python'), ('javascript', 'JavaScript'), ('web', 'Web'), ('database', 'Database'), ('other', 'Other')], default='django', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, default='', help_text='GitHub repository URL (leave blank if none)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, default='', help_text='Live demo URL (leave blank if none)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='bio',
            field=models.TextField(blank=True, default='I am a dedicated Information Technology student at Kirinyaga University, currently in Year 2 pursuing a Bachelor of Science in Information Technology (Expected Graduation: 2028). I possess practical industry experience gained during a 13-week industrial attachment at the ICT Authority of Kenya, where I contributed to software systems in Python and Django, database workflows, and IT support services. I am passionate about clean code, continuous learning, and building practical technology solutions.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, default='palvismugo06@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_tagline',
            field=models.CharField(default='Building practical solutions. Learning continuously. Growing as a developer.', max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='full_name',
            field=models.CharField(default='Pavis Mugo Muruga', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='github_url',
            field=models.URLField(blank=True, default='https://github.com/palvis997'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='github_username',
            field=models.CharField(blank=True, default='palvis997', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_greeting',
            field=models.CharField(default="Hi, I'm Pavis Mugo Muruga", max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_status',
            field=models.CharField(default='Available for opportunities & collaboration', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.TextField(default='Aspiring technology professional with hands-on industrial attachment experience at the ICT Authority of Kenya. Passionate about software development with Python & Django, database management, and IT infrastructure.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='Information Technology Student | Python & Django Developer | IT Support', max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, default='0711652479', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='profession',
            field=models.CharField(default='Information Technology Student | Python & Django Developer | IT Support', max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_description',
            field=models.TextField(default='Pavis Mugo Muruga — Information Technology student at Kirinyaga University, Python & Django developer, and IT support professional with practical industry experience.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Pavis Mugo Muruga', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_title',
            field=models.CharField(default='Information Technology Student | Python & Django Developer | IT Support', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_message',
            field=models.CharField(default='Hello Pavis, I visited your portfolio and would like to connect with you.', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='254711652479', help_text='Include country code without +, e.g., 254XXXXXXXXX', max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming'), ('framework', 'Frameworks'), ('database', 'Databases'), ('data', 'Data & Information Management'), ('tool', 'Tools'), ('it', 'IT & Systems'), ('other', 'Other Skills')], max_length=50),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='category',
            field=models.CharField(choices=[('education', 'Education'), ('experience', 'Industrial Attachment / Experience'), ('project', 'Project & System Development'), ('achievement', 'Achievement'), ('goal', 'Future Milestone')], default='education', max_length=50),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='date',
            field=models.CharField(help_text='e.g., 2026, May – Jul 2026, 2028 (Expected)', max_length=100),
        ),
    ]
