# Generated by Django 5.2.17 on 2026-08-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_currentlybuilding_recommendation_project_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaygroundExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(help_text='Short description of the mini tool or experiment')),
                ('icon', models.CharField(default='fas fa-flask', help_text='Font Awesome icon class', max_length=100)),
                ('status', models.CharField(choices=[('live', '🟢 Live Demo'), ('in_development', '🟡 In Development'), ('experimental', '🔵 Experimental')], default='in_development', max_length=30)),
                ('technology', models.CharField(default='JavaScript, HTML5, CSS3', max_length=200)),
                ('demo_url', models.URLField(blank=True, default='', help_text='Direct demo or live interactive link')),
                ('code_url', models.URLField(blank=True, default='', help_text='GitHub or code snippet URL')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Playground Experiment',
                'verbose_name_plural': 'Playground Experiments',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='featured',
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=True, help_text='Show in Featured Projects on Homepage'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('live', '🟢 Live'), ('in_development', '🔵 In Development'), ('temporarily_unavailable', '🟡 Temporarily Unavailable'), ('archived', '⚫ Archived')], default='live', help_text='Current project operational status', max_length=30),
        ),
    ]
