# Generated by Django 5.2.17 on 2026-08-25 09:49

import django.db.models.deletion
import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_playgroundexperiment_alter_project_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional short title', max_length=200)),
                ('image', models.ImageField(help_text='Gallery photo (JPG, PNG, WEBP max 5MB)', upload_to='gallery/', validators=[main.validators.validate_image_file])),
                ('alt_text', models.CharField(blank=True, help_text='Descriptive alt text for accessibility — describe what is in the photo', max_length=200)),
                ('caption', models.CharField(blank=True, help_text='Optional display caption', max_length=300)),
                ('category', models.CharField(choices=[('professional', 'Professional'), ('project', 'Project'), ('experience', 'Experience / Attachment'), ('education', 'Education'), ('other', 'Other')], default='professional', max_length=50)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured gallery sections')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_alt',
            field=models.CharField(blank=True, help_text='Descriptive alt text for the featured image', max_length=200),
        ),
        migrations.AddField(
            model_name='certification',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Descriptive alt text for the certificate image', max_length=200),
        ),
        migrations.AddField(
            model_name='certification',
            name='certificate_pdf',
            field=models.FileField(blank=True, help_text='Certificate document PDF (max 10MB)', upload_to='certifications/pdfs/', validators=[main.validators.validate_document_file]),
        ),
        migrations.AddField(
            model_name='experience',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Descriptive alt text for accessibility', max_length=200),
        ),
        migrations.AddField(
            model_name='experience',
            name='image',
            field=models.ImageField(blank=True, help_text='Photos related to industrial attachment/work (JPG, PNG, WEBP max 5MB)', upload_to='experience/', validators=[main.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Featured image for this blog post (JPG, PNG, WEBP max 5MB)', upload_to='blog/', validators=[main.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='certification',
            name='image',
            field=models.ImageField(blank=True, help_text='Certificate image (JPG, PNG, WEBP max 5MB)', upload_to='certifications/', validators=[main.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Main project cover image (JPG, PNG, WEBP max 5MB)', upload_to='projects/', validators=[main.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='project',
            name='screenshot_1',
            field=models.ImageField(blank=True, help_text='Project screenshot 1 (JPG, PNG, WEBP max 5MB)', upload_to='projects/screenshots/', validators=[main.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='project',
            name='screenshot_2',
            field=models.ImageField(blank=True, help_text='Project screenshot 2 (JPG, PNG, WEBP max 5MB)', upload_to='projects/screenshots/', validators=[main.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='project',
            name='screenshot_3',
            field=models.ImageField(blank=True, help_text='Project screenshot 3 (JPG, PNG, WEBP max 5MB)', upload_to='projects/screenshots/', validators=[main.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='recommendation_letter',
            field=models.FileField(blank=True, help_text='Upload the official recommendation letter PDF (max 10MB)', upload_to='recommendations/', validators=[main.validators.validate_document_file]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph image for social sharing (1200x630px recommended)', upload_to='og/', validators=[main.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile photo for Hero and About sections (JPG, PNG, WEBP max 3MB)', upload_to='profile/', validators=[main.validators.validate_avatar_file]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload official CV/Resume (PDF max 10MB)', upload_to='resume/', validators=[main.validators.validate_document_file]),
        ),
        migrations.CreateModel(
            name='ProjectScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Detailed system screenshot (JPG, PNG, WEBP max 5MB)', upload_to='projects/screenshots/', validators=[main.validators.validate_image_file])),
                ('caption', models.CharField(blank=True, help_text='Screenshot caption/title', max_length=200)),
                ('alt_text', models.CharField(blank=True, help_text='Descriptive text for accessibility', max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='main.project')),
            ],
            options={
                'verbose_name': 'Project Screenshot',
                'verbose_name_plural': 'Project Screenshots',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
